"""Builds a small, relevant text excerpt of a retailer page for LLM dimension extraction.

Generic (not retailer-specific): keeps product JSON-LD, spec-table rows, and text
lines or embedded-script snippets that mention dimension keywords, with a little
context. Navigation, headers/footers, cookie banners, and review/Q&A sections are
skipped; duplicates are removed; the total is capped.
"""
from __future__ import annotations

import html as html_lib
import json
import re
from html.parser import HTMLParser

DEFAULT_MAX_CHARS = 6000
MAX_HTML_CHARS = 3_000_000
_KEYWORD_RE = re.compile(
    r"dimension|\bwidth\b|\bdepth\b|\bheight\b|\boverall\b|product size|assembled|measurement|\bsize\b",
    re.IGNORECASE,
)
# AI-generated retailer summaries are never dimension evidence (not the retailer's own specs).
AI_GENERATED_RE = re.compile(
    r"gen[_-]?ai|\bai[_-]?(?:generated|summary|summaries|overview|insight)|aisummary|conciseSummary|"
    r"machine[_-]?generated|ai-powered|generated by ai|review[_-]?summary",
    re.IGNORECASE,
)
_SKIP_TAGS = {"style", "noscript", "template", "svg", "nav", "header", "footer", "form", "button", "select"}
_SKIP_ATTR_RE = re.compile(r"review|comment|question|answer|\bqna\b|\bq-a\b|cookie|consent|breadcrumb|footer|\bnav", re.I)
_BLOCK_TAGS = {"p", "div", "li", "tr", "br", "h1", "h2", "h3", "h4", "h5", "h6", "section", "td", "th", "dd", "dt", "table", "ul"}
_SCRIPT_WINDOW = 220


class _EvidenceCollector(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.jsonld: list[str] = []
        self.scripts: list[str] = []
        self.rows: list[list[str]] = []
        self.dl_pairs: list[tuple[str, str]] = []
        self.text: list[str] = []
        self._script: str | None = None
        self._buf: list[str] = []
        self._skip_stack: list[str] = []
        self._row: list[str] | None = None
        self._cell: list[str] | None = None
        self._dt: str | None = None
        self._pending: list[str] | None = None

    def handle_starttag(self, tag, attrs):
        attributes = {k.lower(): (v or "") for k, v in attrs}
        if tag == "script":
            self._script = "jsonld" if "ld+json" in attributes.get("type", "").lower() else "script"
            self._buf = []
            return
        if self._skip_stack:
            if tag not in ("br", "img", "input", "meta", "link", "hr", "source"):
                self._skip_stack.append(tag)
            return
        marker = " ".join(attributes.get(k, "") for k in ("id", "class", "role", "aria-label", "data-test", "data-testid"))
        if tag in _SKIP_TAGS or (marker.strip() and (_SKIP_ATTR_RE.search(marker) or AI_GENERATED_RE.search(marker))):
            if tag not in ("br", "img", "input", "meta", "link", "hr", "source"):
                self._skip_stack.append(tag)
            return
        if tag == "tr":
            self._row = []
        elif tag in ("td", "th") and self._row is not None:
            self._cell = []
        elif tag in ("dt", "dd"):
            self._pending = []
        if tag in _BLOCK_TAGS:
            self.text.append("\n")

    def handle_endtag(self, tag):
        if tag == "script" and self._script is not None:
            (self.jsonld if self._script == "jsonld" else self.scripts).append("".join(self._buf))
            self._script = None
            return
        if self._skip_stack:
            if self._skip_stack[-1] == tag:
                self._skip_stack.pop()
            return
        if tag in ("td", "th") and self._cell is not None and self._row is not None:
            self._row.append(_squash("".join(self._cell)))
            self._cell = None
        elif tag == "tr" and self._row is not None:
            self.rows.append(self._row)
            self._row = None
        elif tag == "dt" and self._pending is not None:
            self._dt = _squash("".join(self._pending))
            self._pending = None
        elif tag == "dd" and self._pending is not None:
            if self._dt:
                self.dl_pairs.append((self._dt, _squash("".join(self._pending))))
            self._dt, self._pending = None, None
        if tag in _BLOCK_TAGS:
            self.text.append("\n")

    def handle_data(self, data):
        if self._script is not None:
            self._buf.append(data)
            return
        if self._skip_stack:
            return
        for buffer in (self._cell, self._pending):
            if buffer is not None:
                buffer.append(data)
        self.text.append(data)


def build_dimension_evidence(html: str, max_chars: int = DEFAULT_MAX_CHARS) -> str:
    """Returns newline-separated evidence lines (possibly empty), at most ``max_chars``."""
    collector = _EvidenceCollector()
    try:
        collector.feed(html[:MAX_HTML_CHARS])
        collector.close()
    except Exception:
        pass

    lines: list[str] = []
    for block in collector.jsonld:
        lines.extend(_jsonld_lines(block))
    for row in collector.rows:
        if len(row) >= 2 and _KEYWORD_RE.search(" ".join(row)):
            lines.append(": ".join(cell for cell in row if cell))
    for label, value in collector.dl_pairs:
        if _KEYWORD_RE.search(label + " " + value):
            lines.append(f"{label}: {value}")

    text_lines = [_squash(line) for line in "".join(collector.text).split("\n")]
    text_lines = [line for line in text_lines if line]
    for index, line in enumerate(text_lines):
        if _KEYWORD_RE.search(line) and re.search(r"\d", " ".join(text_lines[index:index + 2])):
            lines.append(line if len(line) <= 400 else _keyword_window(line))
            if not re.search(r"\d", line) and index + 1 < len(text_lines):
                lines.append(text_lines[index + 1][:300])  # label on one line, value on the next

    for script in collector.scripts:
        lines.extend(_script_snippets(script))

    return _dedupe_and_cap(lines, max_chars)


def _jsonld_lines(block: str) -> list[str]:
    try:
        data = json.loads(block.strip())
    except (ValueError, RecursionError):
        return []
    found: list[str] = []

    def walk(node, depth=0):
        if depth > 10:
            return
        if isinstance(node, list):
            for item in node:
                walk(item, depth + 1)
        elif isinstance(node, dict):
            types = node.get("@type")
            names = {str(t).lower() for t in (types if isinstance(types, list) else [types]) if t}
            if names & {"product", "productgroup", "individualproduct", "productmodel"}:
                keep = {k: node[k] for k in ("name", "width", "depth", "height", "size", "additionalProperty") if k in node}
                if len(keep) > 1:
                    found.append("JSON-LD product: " + json.dumps(keep, ensure_ascii=False)[:1500])
                description = node.get("description")
                if isinstance(description, str):
                    for sentence in re.split(r"(?<=[.;])\s+|\n", _strip_tags(description)):
                        if _KEYWORD_RE.search(sentence) and re.search(r"\d", sentence):
                            found.append(_squash(sentence)[:300])
            for key in ("@graph", "hasVariant", "mainEntity"):
                if key in node:
                    walk(node[key], depth + 1)

    walk(data)
    return found


# Embedded data also carries reviews, image descriptions and package/shipping data;
# windows that look like those are dropped (generic JSON markers, not retailer-specific).
_UGC_OR_MEDIA_RE = re.compile(
    r'"(?:author|nickname|reviews?|rating|submitted_at|review_text|question|answer|alt|alt_text|altText)"'
    r"|Gallery|ImageObject|\.(?:jpe?g|png|webp)\b|scene7|/image/",
    re.IGNORECASE,
)
_NOT_PRODUCT_RE = re.compile(r"(?<![a-z])(package|packaging|shipping|carton|box)(?![a-z])", re.IGNORECASE)


def _script_snippets(script: str) -> list[str]:
    """Keyword windows from embedded page data (e.g. server-rendered product JSON)."""
    snippets = []
    for match in re.finditer(r"dimensions?|overall|assembled|product size", script, re.IGNORECASE):
        if _inside_non_product_data(script, match.start()):
            continue  # e.g. "package_dimensions": {...} or "Package Dimensions: ..."
        start = max(0, match.start() - 40)
        raw = script[start: match.end() + _SCRIPT_WINDOW]
        if _UGC_OR_MEDIA_RE.search(raw) or AI_GENERATED_RE.search(script[max(0, match.start() - 300): match.end() + _SCRIPT_WINDOW]):
            continue
        text = _squash(_strip_tags(_decode_js_string(raw)))
        if re.search(r"\d", text):
            snippets.append(text)
        if len(snippets) >= 12:
            break
    return snippets


def _inside_non_product_data(script: str, position: int) -> bool:
    """True when the keyword sits inside a package/shipping object or phrase: a
    package/shipping marker occurs shortly before it with no closing brace/bracket
    or item boundary in between."""
    before = script[max(0, position - 300): position]
    markers = list(_NOT_PRODUCT_RE.finditer(before))
    if not markers:
        return False
    return not re.search(r'[}\]]|",\s*"', before[markers[-1].end():])


def _decode_js_string(text: str) -> str:
    text = re.sub(r"\\u([0-9a-fA-F]{4})", lambda m: chr(int(m.group(1), 16)), text)
    text = text.replace('\\"', '"').replace("\\/", "/").replace("\\n", " ").replace("\\t", " ")
    return html_lib.unescape(text)


def _strip_tags(text: str) -> str:
    return re.sub(r"<[^>]{0,200}>", " ", text)


def _keyword_window(line: str) -> str:
    match = _KEYWORD_RE.search(line)
    start = max(0, match.start() - 60) if match else 0
    return line[start:start + 300]


def _squash(text: str) -> str:
    return " ".join(text.replace(" ", " ").split())


def _dedupe_and_cap(lines: list[str], max_chars: int) -> str:
    seen: set[str] = set()
    kept: list[str] = []
    total = 0
    for line in lines:
        line = _squash(line)
        key = line.lower()
        if not line or key in seen or any(key in other or other in key for other in seen):
            continue
        if total + len(line) + 1 > max_chars:
            break
        seen.add(key)
        kept.append(line)
        total += len(line) + 1
    return "\n".join(kept)
